### ISSUE TITLE
Nuxt Icons unable to resolve the components/global icons when components prefix has been disabled

### ISSUE THREAD

**Issue by xxFREESHROUDxx** [nuxt/icon#124]
I am using nuxt-icon ^0.4.2 and i have auto imports enabled in which the icons are working properly like this:
`
<Icon name="LeafIcon" />   // LeafIcon is icon component inside components/global
`

But when I try to remove/disable suffix for the components folder for auto imports like this in my nuxt.config.ts it is not working (ie. above global icon not working ):
```
export default defineNuxtConfig({
   components: [
      {
         path: '~/components',
         pathPrefix: false
      }
   ]
)}
```

I also tried to enable prefix for components/global folder as that might be the issue causing the global icon not being imported.
```
export default defineNuxtConfig({
   components: [
      {
         path: '~/components',
         pathPrefix: false
      },
      {
         path: '~/components/global',
         pathPrefix: true
      }
   ]
)}
```

Even after doing this I was not able to solve this issue. Is there anything wrong that I have been doing or is it just the issue of nuxt? I just wanted to remove the prefix for components folder as working with larger components nested inside components folder like `components/page/search/TopBanner.vue` would make things complicated as we have to write `<PageSearchTopBanner />` for auto importing that component. Please help on this as I am not able to use the components/global icons for my nuxt-icon.

**Comment by Atinux** [comment]
Could you check in the Nuxt Devtools, in the components tabs the names of your components?

**Comment by xxFREESHROUDxx** [comment]
Component:
![image](https://github.com/nuxt-modules/icon/assets/48503352/c6512eae-11de-428f-969b-839c1cfc13f7)
================================================================================
![image](https://github.com/nuxt-modules/icon/assets/48503352/6be12bca-08c4-4128-bc55-a3ab4d370fea)

**Comment by Atinux** [comment]
I am talking about the Nuxt Devtools

**Comment by xxFREESHROUDxx** [comment]
I can see this `<Icon />` being used in the nuxt devtools. nuxt icon is working but just for the custom icon components inside components/global is not working.

In the user components in nuxt devtools, I can see the name of my custom component inside components/global:
![image](https://github.com/nuxt-modules/icon/assets/48503352/de089e67-e88a-48bf-83c2-038b5a704427)

This is the nuxt icon being used here:
![image](https://github.com/nuxt-modules/icon/assets/48503352/e0d93e14-73c2-4a04-8c22-27d6aad729e1)

**Comment by Atinux** [comment]
Then `ArrowIcon` should work.

You can see a working playground on https://stackblitz.com/edit/nuxt-icon-playground?file=app.vue

**Comment by xxFREESHROUDxx** [comment]
Nope, it's not working as something when that `component: []` is added to the nuxt.config.ts is causing this issue. 
You can check this as I have replicated what I wanted and added some comments there. This should be expected to work but it's not working. I tried workaround like making pathPrefix true for components/global in the nuxt config which also seems to not work.

https://stackblitz.com/edit/nuxt-icon-playground-1kycsn?file=app.vue

**Comment by Atinux** [comment]
Could you try adding the `global: true` ?

**Comment by antfu** [comment]
Close as this should be no longer relevant with Nuxt Icon v1
