### ISSUE TITLE
customCollections error

### ISSUE THREAD

**Issue by grasilife** [nuxt/icon#171]
https://stackblitz.com/edit/nuxt-icon-playground-ixa4jk?file=assets%2Fmy-icons%2Ffoo.svg,nuxt.config.ts,app.vue

**Comment by grasilife** [comment]
https://nuxticonplaygroundixa4jk-rw4p--3000--12d46890.local-credentialless.webcontainer.io/

**Comment by LordLumineer** [comment]
Hey, the issue has already been reported, this is currently a beta function:
https://github.com/nuxt-modules/icon/issues/162#issuecomment-2133496171
