### ISSUE TITLE
Add universal support for color attribute (similar to CSS icons)

### ISSUE THREAD

**Issue by Rednas83** [nuxt/icon#176]
`<Icon name="uil:github" color="red" />`
returns
![image](https://github.com/nuxt/icon/assets/25219229/10fcdec3-bbf1-45e6-96c5-93fd76a79d4d)
**App.config.ts**
```
// https://github.com/nuxt-modules/icon#configuration-%EF%B8%8F
export default defineAppConfig({
  icon: {
    size: "300%", // default <Icon> size applied
    class: "icon", // default <Icon> class applied
    mode: "css", // svg || css
    aliases: {
      nuxt: "logos:nuxt-icon",
    },
  },
})
```

**Comment by antfu** [comment]
Use `style="color:red"` instead.

**Comment by Rednas83** [comment]
This works just like `class="text-red-600"` for tailwind users. But the docs still mentions `color` in the example
![image](https://github.com/nuxt/icon/assets/25219229/e5219f0a-07cb-4dcc-ab52-e285e759ef4f)

Will `color` as a shorthand be supported again or should the docs be updated?

**Comment by danjrwalsh** [comment]
> This works just like `class="text-red-600"` for tailwind users. But the docs still mentions `color` in the example ![image](https://private-user-images.githubusercontent.com/25219229/344604248-e5219f0a-07cb-4dcc-ab52-e285e759ef4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTc2NDQsIm5iZiI6MTcyMDE5NzM0NCwicGF0aCI6Ii8yNTIxOTIyOS8zNDQ2MDQyNDgtZTUyMTlmMGEtMDdjYi00ZGNjLWFiNTItZTI4NWU3NTllZjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDE2MzU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiOTVlOThiZjE0ODZjYmY2NzA4YTVkNWY5ZGQ0NmRjYjZjNjYxOWMwMjQ0MDhkYWQ1MTgxYzk3MGE5YzIxYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R1sYeuBB8rE2Qx4i64s32cicSr1MnOvQGzaAZXOHVvI)
> 
> Will `color` as a shorthand be supported again or should the docs be updated?

The `color` attribute in that reference is regarding the built-in attribute available on the [SVG element](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute), that's why it's below the message _"you can give all the attributes of the native element"_ and has a link to the mozilla doc for SVG.

With that said, I do agree that it's a bit confusing in that context.

When using CSS icons (the default now), you must use `style` or `class`, otherwise for SVG icons you can continue to use `color` like you did previously.

**Comment by Rednas83** [comment]
Ok, I migrated to `style` for now
```
:color="page.name == selected ? settings.color : page.name == 'Alarms' && coptions.alarm ? 'red' : 'black'" // ISSUE: Not supported
:class="page.name == selected ? `text-[${settings.color}]` : page.name == 'Alarms' && coptions.alarm ? 'text-red-600' : 'text-black'" // ISSUE: Only typed colors are supported
:style="{ color: page.name == selected ? settings.color : page.name == 'Alarms' && coptions.alarm ? 'red' : 'black' }" // ISSUE: Little less convenient??
```

Is it an idea to also support the `color` attribute for svg icons?  It would make the library much more universal I think🤔

And perhaps also add universal support `stroke-width` while at it?
