### ISSUE TITLE
Increased build size after updating to v1

### ISSUE THREAD

**Issue by ExEr7um** [nuxt/icon#184]
For me it was increased from `2.91 MB (737 kB gzip)` to `13.5 MB (4.15 MB gzip)`. I understand that it is because icons are now bundled with website to reduce calls to iconify API.

But in my case I can no longer deploy website to Cloudflare free workers because of 1MB limit. As I understand, that limit only applies to scripts, but not assets. So maybe there is a way to store icons as assets, not as scripts.

Or maybe there is some option to disable bundling icons or to bundle only specific icons, not the whole collections.

**Comment by antfu** [comment]
You can disable the bundling by `icon.serverBundle = false`. Later we will figure out a better API to filter the bundled icons to reduce the size.
