### ISSUE TITLE
@nuxt/icon conflicting with @nuxt/ui (and probably with others UI framework which uses "Icon" component)

### ISSUE THREAD

**Issue by ztxone** [nuxt/icon#200]
This Warn appears when some other modules uses component with name "Icon" (for ex with @iconify or @nuxt/ui)

" WARN  Overriding Icon component. You can specify a priority option when calling addComponent to avoid this warning. "

I supposed it happens somewhere inside nuxt's autoimports behind the scene. Even if i don't use any NuxtUi icons anywhere.
If i comment @nuxt/icon (or @nuxt/ui) module in nuxt.config.ts - problem dissapears

Probably for @nuxt/icon would need  some prefix or ability to make some prefix when there are several modules with Icon components

and other thing - this warning doesn't give understanding what should i do exactly ) where i need to "specify a priority option" cuz i don't "calling addComponent" anywhere directly ))) more questions and no answers )

**Comment by skoulix** [comment]
I'm using Polaris Vue which has already an Icon component
https://ownego.github.io/polaris-vue/components/Icon

I'm getting the "[Vue warn]: Component "Icon" has already been registered in target app" message in console.

It would be really great if there is an option to change the Component name with a custom one globally via the nuxt.config file.

**Comment by antfu** [comment]
You can change the component name with:

```ts
export default defineNuxtConfig({
  icon: {
    componentName: 'NuxtIcon'
  }
})
```

**Comment by skoulix** [comment]
Sorry for my ignorance, I went over the docs but it seems I missed this one.

Thank you so much!

**Comment by skoulix** [comment]
I set it up this way but it doesn't seem to have any effect, as mentioned also here https://github.com/nuxt/icon/issues/180

**Comment by skoulix** [comment]
Sorry my bad, it works perfectly.

**Comment by ztxone** [comment]
> Could you give a reproduction? In the latest nuxt/ui it should already include this module and set the rename to it

I'll try to do it

But i think overriding happens because of that
![nuxt-ui import](https://github.com/user-attachments/assets/6fd79bc8-f07b-4261-84e7-7ac051f16a1f)
![nuxt-icon import](https://github.com/user-attachments/assets/6df65997-0a75-4d40-85c3-4d535769a8fa)

**Comment by ztxone** [comment]
Simple screencast of problem

https://github.com/user-attachments/assets/c967b005-723b-4d4f-b163-5b67e4a076e8

**Comment by ztxone** [comment]
> Simple screencast of problem
> 
> @nuxt/ui 2.17.0 @nuxt/icon 1.0.0
> 
> When running with commented module @nuxt/icon - there are no complains When uncomment module @nuxt/icon - there are warnings with overriding "Icon" component
> 
>  Screencast.mp4

Updated @nuxt/icon to 1.1.1  - same warnings

**Comment by ztxone** [comment]
> You can change the component name with:

I can confirm, that changing componentName solves warnings with both modules active!

But default behaviour still gives warning with overriding component
