### ISSUE TITLE
icons not working after disabling SSR with latest  1.1.1 update 

### ISSUE THREAD

**Issue by Neoniq** [nuxt/icon#205]
```
------------------------------
- Operating System: Windows_NT
- Node Version:     v20.14.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      devtools, ssr, app, primevue, css, modules, swiper, icon, dir, components, srcDir, runtimeConfig, alias, compatibilityDate
- Runtime Modules:  @pinia/nuxt@0.5.1, @vueuse/nuxt@10.11.0, nuxt-primevue@3.0.0, @nuxt/icon@1.1.1, @nuxt/eslint@0.3.13, @nuxt/image@1.7.0, nuxt-swiper@1.2.2
- Build Modules:    -
------------------------------
```

` ssr: false,`

icons not working after disabling ssr with latest   ` "@nuxt/icon": "^1.1.1"`  update 
With old  `"@nuxt/icon": "1.0.0",` works fine. Im using custom icons, no iconify whatsoever

icon itself looks like this after update - no content inside svg
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" ssr="true" class="_infoIcon_5ybwn_125 _icon_1nxjn_7 _info_1nxjn_12 icon iconify iconify--icon" width="1em" height="1em" viewBox="0 0 24 24"></svg>
```

```
  icon: {
    fallbackToApi: false,
    mode: 'svg',
    customCollections: [
      {
        prefix: 'icon',
        dir: './src/shared/components/icons'
      }
    ]
  },
```

no errors in console or network too

**Comment by antfu** [comment]
Custom icons would require a server to work. You can set 

```ts
icon: {
   provider: 'server'
}
```

if you are using a SPA with an API server (back to the behavior of v1.0.0)

**Comment by Neoniq** [comment]
> Custom icons would require a server to work. You can set
> 
> ```ts
> icon: {
>    provider: 'server'
> }
> ```
> 
> if you are using a SPA with an API server (back to the behavior of v1.0.0)

The default is supposed to be server, no?
![image](https://github.com/user-attachments/assets/5ab6421c-5b22-429d-a04f-e542a7a5b3b5)

**Comment by Neoniq** [comment]
adding `provider: 'server'` fixes issue tho
