### ISSUE TITLE
Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by QaahirStewart** [nuxt/icon#217]
Reproduction:
https://github.com/QaahirStewart/icontest

It seems that when icon name is bounded with access a property ex(.dot after emptyIconData)   <Icon :name="emptyIconData.logo" /> this error is getting produced.

**Comment by antfu** [comment]
Note that the `name` field is a required string - you should do some checks to avoid passing in undefined or null - while I added some additional guards to bypass that, it's still recommended to ensure you are passing a valid icon name.

**Comment by spencerjsmall** [comment]
@antfu I'm also experiencing this throughout my app after upgrading to Nuxt UI 2.18 (now utilizing Nuxt Icon exclusively). I believe the error is thrown repeatedly when the `name` value I pass to `UIcon` is computed and therefore its evaluation is delayed. Shouldn't this only throw a warning, not a breaking error?
