### ISSUE TITLE
Issues when Prerender with `nuxt generate`

### ISSUE THREAD

**Issue by Mat4m0** [nuxt/icon#220]
When I used the latest [Nuxt UI Pro Docs Theme](https://github.com/nuxt-ui-pro/docs) and added Nuxt Scripts, I encountered some missing icons.

**To reproduce:**

- Clone "Nuxt UI Pro Docs"
- Add Nuxt Scripts as dependency
- Deploy to Vercel with `npx nuxi generate`
- Find missing Icons 

**Missing Icons when Client Side Rendering:**
<img width="940" alt="image" src="https://github.com/user-attachments/assets/acdfa7df-ded1-4811-8305-320ca99303c2">

**Cannot Find icons:**
<img width="1179" alt="image" src="https://github.com/user-attachments/assets/fe1135ff-9ef2-4157-bd58-dc7e00f566c1">

**Server Rendered:** 
<img width="810" alt="image" src="https://github.com/user-attachments/assets/4f5d37a0-b5f1-4521-b566-f0a74c034427">

Maybe this is also interesting for you @benjamincanac, @harlan-zw

**Comment by antfu** [comment]
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example). Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by Mat4m0** [comment]
You find my [reproduction repo here](https://github.com/Mat4m0/reproduction_nuxt_icon)

To Reproduce:

1) Clone reproduction repo, install deps
2) `pnpm nuxi generate`
3) Check output: `npx serve .output/public ` 

=> You will find the color mode switcher is missing either the moon or soon icon:
<img width="621" alt="image" src="https://github.com/user-attachments/assets/ccf18dbe-b403-4604-a7a7-5ebe32d38d4c">
