### ISSUE TITLE
Custom collections not working in `ssr: false` when all icons are rendered with `svg` mode

### ISSUE THREAD

**Issue by zigomir** [nuxt/icon#228]
It doesn't matter wether you specify svg via `app.config.ts` or via `mode` prop of the `Icon` component.

Reproduction branch: https://github.com/zigomir/icon/tree/local-fs-svg-issue-reproduction and diff https://github.com/nuxt/icon/compare/main...zigomir:icon:local-fs-svg-issue-reproduction

Workaround is to include at least one icon from the custom collection in `css` mode like so:

```vue
<template>
  <Icon
    name="custom1:nuxt-v3"
    size="64"
    mode="svg"
  />

  <!--
    WORKAROUND: load at least one icon in css mode to make svg mode work.
    It doesn't even have to be the same icon
  -->
  <Icon
    style="display: none;"
    name="custom1:nuxt-v1"
    size="64"
    mode="css"
  />
</template>
```

This might also be related to https://github.com/nuxt/icon/issues/212

**Comment by awacode21** [comment]
This did not fix #212
