### ISSUE TITLE
Icons Load on SSR Slow

### ISSUE THREAD

**Issue by moshetanzer** [nuxt/icon#233]
Hi @antfu 

Thanks for this great lib. 

When using ssr icons take ages to load. For eg if I have a toast with an icon, toast shows and then only a second or so later icon shows. Have I missed something?

Am just using nuxt/icon as part of Nuxt UI

Regards

**Comment by antfu** [comment]
Can you share a minimal reproduction? That deps on which mode you use and your production servers' location (if icons are loaded remotely)

**Comment by moshetanzer** [comment]
Will try reproduce. Just a nuxt ui project self hosted. Will a video help?

**Comment by antfu** [comment]
Better a code repo so I can test myself and play with solutions

**Comment by moshetanzer** [comment]
Here is repro - go into mobile view, each time you refresh page and access mobilve nav menu icons take a second to show
https://landing-template.nuxt.dev/

thanks!

**Comment by antfu** [comment]
Seems working fine for me, the icons should also be cached in multiple requests - do you have a more specific repro steps with the source code repo?

**Comment by moshetanzer** [comment]
not sure what you mean "working fine for me" - the icons take a second to show - this isnt even an ssr:true.

https://github.com/user-attachments/assets/09515801-647b-4fc1-b02d-c22bd208a5b5

**Comment by moshetanzer** [comment]
Hey @antfu 

just following up on this...

**Comment by antfu** [comment]
I insist on having a minimal reproduction so I can examine it more thoroughly and find the cause; screenshots and videos are not reproductions.

**Comment by antfu** [comment]
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by moshetanzer** [comment]
Hey @antfu,

Not sure what you mean - provided - https://landing-template.nuxt.dev...

**Comment by antfu** [comment]
Oh you mean https://github.com/nuxt-ui-pro/landing? 😂

**Comment by moshetanzer** [comment]
Sorry! Yes should have put the gh link. I hear ok. Any current workaround for nuxt/ui? (since they dont use the tailwind icon plugins as far as i know anymore even thought it is mentioned here that they do - https://github.com/nuxt/icon/issues/34#issuecomment-2003339110)

**Comment by antfu** [comment]
Please give a try with https://github.com/nuxt/icon/issues/34#issuecomment-2312164445, it should be resolved.
