### ISSUE TITLE
Icons not showing because of the server middleware

### ISSUE THREAD

**Issue by kieutrongthien** [nuxt/icon#241]
I just created this issue because I think it'll help someone else if they have a problem like me.

**What happened ?**

The icons are not showing even if you have deleted **yarn.lock**, **package-lock.json**, **node_modules** and reinstall all of them.

**Reason**

I've created a middleware in **server/middlewares** folder. This middleware checks the current route path and passes if the path does not require authentication. Otherwise, get the JWT token and verify it.

```ts
import { getUserToken } from "../utils"

export default defineEventHandler(async (event) => {
  if (!event.path.startsWith("/api")) return;
  if (event.path.startsWith('/api/auth')) return;

  const user = await getUserToken(event)  

  if (!user) {
    return send(event, JSON.stringify(jsonResponse({
      success: false,
      code: 401,
      msg: 'Unauthorized'
    })), "application/json");
  }

  if (event.path.startsWith("/api/admin") && user && user.role !== 'ADMIN') {
    const result = jsonErrorResponse(403, "You don't have permission to access this API(s)");
    return send(event, JSON.stringify(result), "application/json");    
  }

  event.context.user = user
});
```

I just figured out **@nuxt/icon** library is running a route at **/api/_nuxt_icon**:[https://github.com/nuxt/icon/blob/main/src/module.ts#L73](https://github.com/nuxt/icon/blob/main/src/module.ts#L73)

So, if you facing a problem like me. Please add more a condition to your server middleware:

```ts
...
if (!event.path.startsWith("/api")) return;
if (event.path.startsWith('/api/_nuxt_icon')) return; #Here
if (event.path.startsWith('/api/auth')) return;
...
```

Finally, thanks @atinux for this library

Regards

**Comment by antfu** [comment]
Thanks for the solution! Also you can customize the path if you prefer: https://github.com/nuxt/icon/blob/c8af4db2b0d5e9bb1935cda3e97f1eb89881c44a/src/schema-types.ts#L122-L129
