### ISSUE TITLE
On dev: 404 for icons that were not visible on initial page load

### ISSUE THREAD

**Issue by MickL** [nuxt/icon#251]
Since I upgraded to 1.4.x icons that were not there on initial page load (e.g. toggle by v-if or even when navigating pages) are all missing with errors in console for each:

```
GET http://localhost:3001/api/_nuxt_icon/material-symbols.json?icons=add 404 (Cannot find any route matching /_nuxt_icon/material-symbols.json.)
```

This applies to dev only. On prod it works fine.

I made a reproduction repo but I couldnt reproduce there. I dont have any configuration for icons in my nuxt.config and I just use them as shown in the docs with no additional config:

```
<Icon name="uil:github" />
```

Nuxi info:
```
------------------------------
- Operating System: Darwin
- Node Version:     v21.6.1
- Nuxt Version:     3.13.0
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  bun@1.1.26
- Builder:          -
- User Config:      extends, modules, future, experimental, runtimeConfig, scripts, i18n, routeRules, ignore, site, app, ogImage, sitemap, plausible
- Runtime Modules:  @nuxt/scripts@^0.6.4, @nuxtjs/seo@2.0.0-rc.19, @nuxtjs/tailwindcss@^6.12.0, @vee-validate/nuxt@^4.13.2, nuxt-og-image, @nuxtjs/plausible@^1.0.2
- Build Modules:    -
------------------------------
```

**Comment by MickL** [comment]
I just realized that it tries to load from `/api` but I have a proxy route roule for `/api/**` leading to my backend api.

Is there any possibility to change this path?

**Comment by VictorioBerra** [comment]
My mind is blown that `/_nuxt_icon` is not the default.
