### ISSUE TITLE
A couple of doubts about Nuxt icon

### ISSUE THREAD

**Issue by molul** [nuxt/icon#254]
Hi there! I started a Nuxt project with Nuxt icon module, but moved to using Iconify package for a couple of reasons, and I thought I'd better ask just in case there's a solution to both that allows me to get back to Nuxt icon, which seemed a bit lighter: 

1 - I have a component that changes the icon depending on a "status" ref variable. With iconify, the transition is immediate, but with Nuxt icon, there's no icon for half a second (a solid color square appears instead), and sometimes the initial icon is not loaded at all, and I have to click it to change the status and finally load it (it doesn't happen with iconify). If you need a build to see the issue, please let me know.

2 - With iconify, I can use tailwind bg-* classes in Icon component for changing the icon background, and text-* for icon color. But with Nuxt icon, bg-* and text-* both change the icon color, so I have to wrap the Icon component in a div in order to apply a background color. Is there any other way to change the background color with Nuxt icon? Or, are there plans to add support for background color? 

Thanks a lot beforehand :)

**Comment by antfu** [comment]
1. Can you provide some examples of how you use the icons?
2. You are right. This is how CSS-based icon solution work (you can read https://antfu.me/posts/icons-in-pure-css for more details). Iconify also has this mode available, while we also have the SVG mode available. But we choose the CSS mode as the default coz we believe it's the most performant way to do so (so you don't create hundreds of SVG dom elements and does not have hydration issues). Of course, if you want, you can switch to the SVG mode per-icon or globally to apply the background color. Or wrapping an other DOM element would be the way to go with the CSS mode

**Comment by molul** [comment]
1 - Well, I'd like to, but I rolled back to using Nuxt Icon and that artifact is not happening anymore. Not sure what I did before, but fortunately it's gone. Sorry for the confusion.

2 - Ah, I see. Good to know. Thanks!
