### ISSUE TITLE
`loadIcon` always shows console warning despite successful icon load

### ISSUE THREAD

**Issue by geforseN** [nuxt/icon#271]
**Description:**

After updating the `@nuxt/icon` package to [version 1.5.4](https://www.npmjs.com/package/@nuxt/icon/v/1.5.4), I started seeing the following warning messages in the console:

```
[Icon] loading icon <name> timed out after 500ms
```

I increased the `icon.fetchTimeout` in `nuxt.config.ts` to higher value, such as 15000, but the warning still appears, even though my icons are loaded correctly within the specified time.

**Steps to reproduce:**

1. Update `@nuxt/icon` to version 1.5.4.
2. Optionally, set `icon.fetchTimeout` in `nuxt.config.ts` to a higher value than the default (500):
   ```js
   export default defineNuxtConfig({
     icon: {
       fetchTimeout: 15000, // 15 seconds
     },
   });
   ```
3. Run the application.
4. Check the console for warnings like:
   ```
   [Icon] loading icon <name> timed out after <icon.fetchTimeout>ms
   ```

**Expected behavior:**

If the icons are loaded correctly within the specified timeout (in this case, 15 seconds), the warning should not appear in the console.

**Actual behavior:**

The warning is still shown, even though the icons are successfully loaded.

**Comment by bloor** [comment]
Thankyou So VERY MUCH !
Holly f.. those warning were annoying in terminal.
