### ISSUE TITLE
[Icon] loading icon <...> timed out after 500ms

### ISSUE THREAD

**Issue by LynxTR** [nuxt/icon#273]
![Image](https://github.com/user-attachments/assets/054795cf-7f56-4662-92f7-44bda5132d79)
![Image](https://github.com/user-attachments/assets/b982e5e3-11c2-4e63-8147-4969b1ccbc0d)

**Reproduction:**

npx nuxi@latest init -t ui

**Description:**

I'm encountering a timeout issue. I’ve tried setting serverBundle to 'remote', 'local', and false, as well as using different package managers like pnpm and npm, but the issue persists. Not only locally installed collections effected by this, the internally used heroicons collection by nuxt/ui also throws timeout. Icons are being displayed on browser. Same log visible on browser as well, shared as screenshots.

**Logs:**

{"message":"[warn] [Icon] loading icon `game-icons:wolf-howl` timed out after 500ms\n","timestamp":"2024-10-07T10:22:24.175Z","type":"err","process_id":12,"app_name":"<...>"}
{"message":"[warn] [Icon] loading icon `ph:magnifying-glass-duotone` timed out after 500ms\n","timestamp":"2024-10-07T10:22:24.176Z","type":"err","process_id":12,"app_name":"<...>"}
{"message":"[warn] [Icon] loading icon `ph:user-duotone` timed out after 500ms\n","timestamp":"2024-10-07T10:22:24.176Z","type":"err","process_id":12,"app_name":"<...>"}

**Comment by LynxTR** [comment]
duplicate of #271

**Comment by bloor** [comment]
Thankyou So VERY MUCH !
Holly f.. those warning were annoying in terminal.
