### ISSUE TITLE
(node:17640) [DEP0155] DeprecationWarning: Use of deprecated trailing slash pattern mapping "./" in the "exports"

### ISSUE THREAD

**Issue by tinegaCollins** [nuxt/icon#287]
field module resolution of the package at C:\Users\colli\OneDrive\Desktop\uppr_v1\node_modules\@iconify\utils\package.json imported from C:\Users\colli\OneDrive\Desktop\uppr_v1\node_modules. Mapping specifiers ending in "/" is no longer supported. (Use `node --trace-deprecation ...` to show where the warning was created) - I am  getting this error when running nuxt buid

**Comment by antfu** [comment]
Duplicated #140
