### ISSUE TITLE
[Feature] include `.yml` files in `scanSourceFiles` for `clientBundle.scan`

### ISSUE THREAD

**Issue by ZTL-UwU** [nuxt/icon#288]
Sometimes in Nuxt Content, icons are used in the [`_dir.yml`](https://content.nuxt.com/usage/navigation#custom-keys) files, which will escape file scanner when using `clientBundle.scan`.

https://github.com/nuxt/icon/blob/0939395def276ffb21862bdb79f0211d2e9aa47b/src/scan.ts#L15-L20

Can we add a `.yml` suffix to `globInclude` or perhaps add a config for this.

**Comment by antfu** [comment]
Added in 31bbc52a6b637c987d4d63da689dc9e42f8fc0b5
