### ISSUE TITLE
Disable console.log

### ISSUE THREAD

**Issue by dethdkn** [nuxt/icon#299]
Since this commit 36e38c32f8f1f61570080e4e95f51cf249229a1a (I guess), when I open pm2 logs, I get a lot of console.log from nuxt icon
![Image](https://github.com/user-attachments/assets/af2220bf-8c2e-4437-b806-10998172ff6d)

Is there a way to disable it?

**Comment by antfu** [comment]
Fixed in 36e38c32f8f1f61570080e4e95f51cf249229a1a
