### ISSUE TITLE
Icon name in unocss format is getting parsed incorrectly

### ISSUE THREAD

**Issue by TechAkayy** [nuxt/icon#303]
"i-material-symbols-light-mode-outline" parses incorrectly as `material-symbols-light:mode-outline` (note the position of the colon in the string) instead of `material-symbols:light-mode-outline`

`<Icon name="i-material-symbols-light-mode-outline" />` doesn't work. // uses unocss format
`<Icon name="material-symbols:light-mode-outline" />` works fine. // iconify format

**Reproduction**

https://stackblitz.com/edit/nuxt-icon-playground-dcclkm?file=app.vue

Thank you for looking into this. Cheers!

**Comment by antfu** [comment]
Emm, I see. However, I think it isn't "parses incorrectly" but actually ambiguous. I don't think at the technical level this is solvable - it's also why Iconify would suggest using `:`. In uno it's also possible to use `:` btw.
