### ISSUE TITLE
Missing data-v attribute when used in template slot in v1.8.1

### ISSUE THREAD

**Issue by Janus-thg** [nuxt/icon#304]
After upgrading from `1.7.6` to `1.8.1`, I encountered that scoped styling from a parent component where an `<Icon />` was used in a slot, no longer applied to the Icon. It looks like the `data-v` id that vue uses for scoped styling, is not inherited, although the class is present.

Stackblitz reproduction:
https://stackblitz.com/edit/nuxt-icon-missing-data-v?file=app.vue

Possibly related to #301 and #300 

```
❯ npx nuxt info
Working directory: /home/projects/nuxt-icon-missing-data-v
Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.14.1592
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/icon@1.8.1
- Build Modules:    -
------------------------------```

**Comment by antfu** [comment]
Can you try 1.8.2?

**Comment by antfu** [comment]
I can confirm it's fixed in the repro.
