### ISSUE TITLE
Hydration mismatch with `useId()` if `<Icon />` is used on parent component

### ISSUE THREAD

**Issue by Perdolique** [nuxt/icon#310]
### Problem

I'm using `useId()` provided by Vue to connect `input` and `label` together (`CustomInput` component). But having `<Icon />` somewhere on the page makes a hydration mismatch on `CustomInput`.

<details>
<summary>Warning example</summary>

```
[Vue warn]: Hydration attribute mismatch on <label for=​"v-1-0">​Woof​</label>​ 
  - rendered on server: for="v-1-0"
  - expected on client: for="v-0-0"
  at <CustomInput label="Woof" > 
  at <TestComponent> 
  at <App key=4 > 
  at <NuxtRoot>
```
</details>

Every new icon increases the `id` generated on the server to `1`.

### Reproduction

[Stackblitz](https://stackblitz.com/edit/github-pz2kcg-xhujss?file=app%2Fcomponents%2FTestComponent.vue)

**Comment by antfu** [comment]
Fixed in https://github.com/nuxt/icon/commit/f5e74f592a10da1e0e56dfad137e19baf70f39b8
