### ISSUE TITLE
Allow extension of iconMatchRegex to support custom packages

### ISSUE THREAD

**Issue by Quasarman** [nuxt/icon#311]
I am having the same issue as https://github.com/nuxt/icon/issues/252.

This could be easily resolved if we were able to extend the `iconMatchRegex` variable. Then you just need to set `scan: true` and all the icons would be bundled with the client when `ssr: false`, without the hassle of having a custom iconify endpoint etc.

And since the app gets wrapped via capacitor and is installed on the users device anyways, I do not want to make any calls to some server to fetch icons.

I manually added my custom collection name (`cis`) in the installed module and built my app for capacitor (`ssr: false`) and it worked perfectly.

Important line from my package.lock
```json
{
    "dependencies": {
        ...
    },
    "devDependencies": {
        "@iconify-json/cis": "file:./assets/icon-sets/cis",
        "@iconify-json/wi": "^1.2.0",
        ....
    }
}

```

**Comment by antfu** [comment]
That's an interesting usage. I wonder why the custom collections do not work for you? Having this would be a bit tricky as it might result in some parts of the integration think the collection actually exists on Iconify - but yeah, it might be possible.

I don't actually mind to give it a try. Would like to initiate a PR to show how would you design the API? Thanks

**Comment by Quasarman** [comment]
Hey @antfu ,

Thanks for your response! Custom collections do not work for us since we have +2500 icons --> loads of small files in a devcontainer cause performance issues during sync / first startup.

I will give it a shot!

BR
Johannes
