### ISSUE TITLE
Custom local icons are not rendering

### ISSUE THREAD

**Issue by stijns96** [nuxt/icon#326]
I'm experiencing an issue with my local font awesome pro setup.

I'm using Nuxt UI Pro and the issue looks like it's Nuxt Icon related.

<img width="1407" alt="Image" src="https://github.com/user-attachments/assets/842b0d0f-7437-44a4-bb8f-1f4bded3ed93" />

<img width="1439" alt="Image" src="https://github.com/user-attachments/assets/c181ed5c-ed16-468b-907f-6dd4facdd9db" />

As you can see, it doesn't work. @benjamincanac  from Nuxt UI already mentioned me to use the `i-` syntax: `i-fa-light-caret-right`. This doesn't work as well...

I'm I doing something wrong?

Context: https://github.com/nuxt/ui/issues/2590

**Comment by benjamincanac** [comment]
@stijns96 As mentioned in nuxt/ui#2590, this has been fixed in `@nuxt/icon` already.
