### ISSUE TITLE
Feature Request: Built-in API provider for custom IconifyJSON

### ISSUE THREAD

**Issue by Aareksio** [nuxt/icon#97]
### Motivation

As is, iconify is great for free, public icon sets. For commercial purposes, you may want to use commercially licensed icon pack - the most popular example being [Font Awesome Pro](https://fontawesome.com/icons). Iconify [already provides](https://iconify.design/docs/libraries/tools/examples/import-fa-pro.html) a way of converting custom icon packs into `IconifyJSON` definition. However, Including the whole `IconifyJSON` in the app is costly, it can easily weigh over 100 kB (raw). Therefore, iconify by default uses API provider to deliver only the requested icon definitions on demand. It is currently not possible to easily host your own icon packs definitions.

### Feature Request
Since nuxt already hosts server routes, it would be great if the module could provide a streamlined method of hosting Iconify API provider. This way, the end-user could easily use their non-free icon packs benefiting from the on-demand architecture of iconifi's `loadIcon`.

Example module configuration could look like this:
```ts
defineAppConfig({
  nuxtIcon: {
    customCollections: [
      resolve('./assets/icons/collections/my-icons.json')
    ]
  }
})
```

To achieve this, the module would have to expose http API conforming to the [Iconify API standard](https://iconify.design/docs/api/icon-data.html#query). The API is very straight forward

Example definition:
```json
{
  "prefix": "my-icons",
  "lastModified": 1691181322,
  "icons": {
    "a": { "body": "<path d=\"_path_a_\"/>" },
    "b": { "body": "<path d=\"_path_b_\"/>" },
    "c": { "body": "<path d=\"_path_c_\"/>" }
  },
  "width": 24,
  "height": 24,
}
```

Example API response to `GET /api/iconify-provider/my-icons.json?icons=a,c`
```json
{
  "prefix": "my-icons",
  "icons": {
    "a": { "body": "<path d=\"_path_a_\"/>" },
    "c": { "body": "<path d=\"_path_c_\"/>" }
  },
  "width": 24,
  "height": 24,
}
```

Module would have to register the custom provider with iconify library:
```ts
import { addAPIProvider } from '@iconify/vue'
addAPIProvider('nuxt', { resources: ['/api/iconify-provider'] })
```

And the icons should be usable as per example:
```html
<icon name="@nuxt:my-icons:a"/>
<icon name="@nuxt:my-icons:c"/>
```

**Comment by JohnCampionJr** [comment]
Any chance we could get this soon with the new version now done?

**Comment by antfu** [comment]
I believe you could do that already:

https://github.com/nuxt/icon/blob/cb44eede9993ed287a41c47b63d790d17a0d37a7/src/types.ts#L66-L70

**Comment by JohnCampionJr** [comment]
@antfu any chance you could provide a sample showing how to load icons from a custom json file?

**Comment by reslear** [comment]
hi @antfu pls reopen because this not implemented 

https://iconify.design/docs/libraries/tools/import/json.html

https://github.com/nuxt/icon/blob/548c3bb105448747f1eaac5653c85a40ec3cd51f/src/collections.ts#L33

**Comment by Aareksio** [comment]
@reslear

It _works_. It consumes awful lot of memory during build, but works. I never got to debugging the memory issue properly, but here is the demo showcasing importing collection as IconifyJSON: https://stackblitz.com/edit/github-rpgvsa?file=nuxt.config.ts. If the possible memory issue rings a bell, I'd appriciate 15 minutes of thought - maybe it is trivial to fix. Otherwise I'll maybe make proper reproduction someday 😉

**Comment by reslear** [comment]
@Aareksio I don't want to generate a ts file
